# SPDX-FileCopyrightText: LakeSoul Contributors
# 
# SPDX-License-Identifier: Apache-2.0
spark: 
  deploy: "local"

flink:
  deploy: "k8s"
  jobmanager: "flink-jobmanager.lakesoul-basic-env.svc.cluster.local:8081"

init:
  type: "flink" 
  name: "DataInit"
  entry: "com.dmetasoul.e2e.FlinkDataInit"
  mode: "application"

# sink means write to lakesoul
sinks:
  - type: "flink"
    name: "DataSink"
    entry: "com.dmetasoul.e2e.FlinkDataSink"
    mode: "application"

# source means read from lakesoul
sources:
  - type: "flink"
    name: "DataSource"
    entry: "com.dmetasoul.e2e.FlinkDataSource"
    mode: "application"